export const footerLinks = [
    {
      title: "Learn with us",
      links: [
        { title: "VocabTrainer™", url: "/" },
        { title: "Word of the day", url: "/" },
        { title: "Dictionary", url: "/" },
        { title: "Vocabulary lists", url: "/" },
      ],
    },
    {
      title: "Teach with us",
      links: [
        { title: "How it works", url: "/" },
        { title: "Blog", url: "/" },
        { title: "For schools and districts", url: "/" },
        { title: "Contact sales", url: "/" },
      ],
    },
    {
      title: "Resources",
      links: [
        { title: "Teaching resources", url: "/" },
        { title: "Learner resources", url: "/" },
        { title: "Help articles/FAQ", url: "/" },
        { title: "ESL/ELL resources", url: "/" },
      ],
    },
];

export const countries = [
  { title: "Define Language", value: "" },
  { title: "Afrikaans", value: "af" },
  { title: "Albanian", value: "sq" },
  { title: "Amharic", value: "am" },
  { title: "Arabic", value: "ar" },
  { title: "Armenian", value: "hy" },
  { title: "Azerbaijani", value: "az" },
  { title: "Basque", value: "eu" },
  { title: "Belarusian", value: "be" },
  { title: "Bengali", value: "bn" },
  { title: "Bosnian", value: "bs" },
  { title: "Bulgarian", value: "bg" },
  { title: "Catalan", value: "ca" },
  { title: "Cebuano", value: "ceb" },
  { title: "Chichewa", value: "ny" },
  { title: "Chinese (Simplified)", value: "zh-CN" },
  { title: "Chinese (Traditional)", value: "zh-TW" },
  { title: "Corsican", value: "co" },
  { title: "Croatian", value: "hr" },
  { title: "Czech", value: "cs" },
  { title: "Danish", value: "da" },
  { title: "Dutch", value: "nl" },
  { title: "English", value: "en" },
  { title: "Esperanto", value: "eo" },
  { title: "Estonian", value: "et" },
  { title: "Filipino", value: "tl" },
  { title: "Finnish", value: "fi" },
  { title: "French", value: "fr" },
  { title: "Frisian", value: "fy" },
  { title: "Galician", value: "gl" },
  { title: "Georgian", value: "ka" },
  { title: "German", value: "de" },
  { title: "Greek", value: "el" },
  { title: "Gujarati", value: "gu" },
  { title: "Haitian Creole", value: "ht" },
  { title: "Hausa", value: "ha" },
  { title: "Hawaiian", value: "haw" },
  { title: "Hebrew", value: "iw" },
  { title: "Hindi", value: "hi" },
  { title: "Hmong", value: "hmn" },
  { title: "Hungarian", value: "hu" },
  { title: "Icelandic", value: "is" },
  { title: "Igbo", value: "ig" },
  { title: "Indonesian", value: "id" },
  { title: "Irish", value: "ga" },
  { title: "Italian", value: "it" },
  { title: "Japanese", value: "ja" },
  { title: "Javanese", value: "jw" },
  { title: "Kannada", value: "kn" },
  { title: "Kazakh", value: "kk" },
  { title: "Khmer", value: "km" },
  { title: "Kinyarwanda", value: "rw" },
  { title: "Korean", value: "ko" },
  { title: "Kurdish (Kurmanji)", value: "ku" },
  { title: "Kyrgyz", value: "ky" },
  { title: "Lao", value: "lo" },
  { title: "Latin", value: "la" },
  { title: "Latvian", value: "lv" },
  { title: "Lithuanian", value: "lt" },
  { title: "Luxembourgish", value: "lb" },
  { title: "Macedonian", value: "mk" },
  { title: "Malagasy", value: "mg" },
  { title: "Malay", value: "ms" },
  { title: "Malayalam", value: "ml" },
  { title: "Maltese", value: "mt" },
  { title: "Maori", value: "mi" },
  { title: "Marathi", value: "mr" },
  { title: "Mongolian", value: "mn" },
  { title: "Myanmar (Burmese)", value: "my" },
  { title: "Nepali", value: "ne" },
  { title: "Norwegian", value: "no" },
  { title: "Odia (Oriya)", value: "or" },
  { title: "Pashto", value: "ps" },
  { title: "Persian", value: "fa" },
  { title: "Polish", value: "pl" },
  { title: "Portuguese", value: "pt" },
  { title: "Punjabi", value: "pa" },
  { title: "Romanian", value: "ro" },
  { title: "Russian", value: "ru" },
  { title: "Samoan", value: "sm" },
  { title: "Scots Gaelic", value: "gd" },
  { title: "Serbian", value: "sr" },
  { title: "Sesotho", value: "st" },
  { title: "Shona", value: "sn" },
  { title: "Sindhi", value: "sd" },
  { title: "Sinhala", value: "si" },
  { title: "Slovak", value: "sk" },
  { title: "Slovenian", value: "sl" },
  { title: "Somali", value: "so" },
  { title: "Spanish", value: "es" },
  { title: "Sundanese", value: "su" },
  { title: "Swahili", value: "sw" },
  { title: "Swedish", value: "sv" },
  { title: "Tajik", value: "tg" },
  { title: "Tamil", value: "ta" },
  { title: "Tatar", value: "tt" },
  { title: "Telugu", value: "te" },
  { title: "Thai", value: "th" },
  { title: "Turkish", value: "tr" },
  { title: "Turkmen", value: "tk" },
  { title: "Ukrainian", value: "ur" },
  { title: "Urdu", value: "ug" },
  { title: "Uyghur", value: "uz" },
  { title: "Uzbek", value: "vi" },
  { title: "Vietnamese", value: "cy" },
  { title: "Xhosa", value: "xh" },
  { title: "Yiddish", value: "yi" },
  { title: "Yoruba", value: "yo" },
  { title: "Zulu", value: "zu" },
  { title: "Hebrew Two", value: "he" },
  { title: "Chinese (Simplified) Two", value: "zh" },
]